# Rust MEV Engine Configuration v3.6.0
version = "3.6.0"
mode = "production"

[database]
connection_string = "postgresql://user:pass@localhost/mev_engine"
max_connections = 20
min_connections = 5

# RPC Endpoints Configuration
# 100+ endpoints across multiple chains for redundancy
[[rpc_endpoints]]
chain = "ethereum"
url = "wss://eth-mainnet.alchemyapi.io/v2/YOUR_API_KEY_1"
weight = 10
max_requests_per_second = 100

[[rpc_endpoints]]
chain = "ethereum"
url = "wss://mainnet.infura.io/ws/v3/YOUR_API_KEY_2"
weight = 10
max_requests_per_second = 100

[[rpc_endpoints]]
chain = "ethereum"
url = "wss://eth.getblock.io/YOUR_API_KEY/mainnet/"
weight = 8
max_requests_per_second = 80

[[rpc_endpoints]]
chain = "ethereum"
url = "wss://ethereum.publicnode.com"
weight = 5
max_requests_per_second = 50

[[rpc_endpoints]]
chain = "ethereum"
url = "wss://rpc.ankr.com/eth_ws/YOUR_API_KEY"
weight = 8
max_requests_per_second = 80

[[rpc_endpoints]]
chain = "ethereum"
url = "wss://eth-mainnet.nodereal.io/ws/v1/YOUR_API_KEY"
weight = 7
max_requests_per_second = 70

[[rpc_endpoints]]
chain = "ethereum"
url = "wss://api.zmok.io/mainnet/ws/YOUR_API_KEY"
weight = 6
max_requests_per_second = 60

[[rpc_endpoints]]
chain = "ethereum"
url = "wss://ethereum.blockpi.network/v1/ws/YOUR_API_KEY"
weight = 7
max_requests_per_second = 70

[[rpc_endpoints]]
chain = "ethereum"
url = "wss://eth-mainnet.public.blastapi.io"
weight = 5
max_requests_per_second = 50

[[rpc_endpoints]]
chain = "ethereum"
url = "wss://mainnet.gateway.tenderly.co"
weight = 6
max_requests_per_second = 60

# Arbitrum endpoints
[[rpc_endpoints]]
chain = "arbitrum"
url = "wss://arb-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
weight = 10
max_requests_per_second = 100

[[rpc_endpoints]]
chain = "arbitrum"
url = "wss://arbitrum-mainnet.infura.io/ws/v3/YOUR_API_KEY"
weight = 10
max_requests_per_second = 100

[[rpc_endpoints]]
chain = "arbitrum"
url = "wss://arbitrum.publicnode.com"
weight = 5
max_requests_per_second = 50

[[rpc_endpoints]]
chain = "arbitrum"
url = "wss://rpc.ankr.com/arbitrum_ws/YOUR_API_KEY"
weight = 8
max_requests_per_second = 80

[[rpc_endpoints]]
chain = "arbitrum"
url = "wss://arbitrum.getblock.io/YOUR_API_KEY/mainnet/"
weight = 7
max_requests_per_second = 70

[[rpc_endpoints]]
chain = "arbitrum"
url = "wss://arbitrum-one.public.blastapi.io"
weight = 5
max_requests_per_second = 50

# Optimism endpoints
[[rpc_endpoints]]
chain = "optimism"
url = "wss://opt-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
weight = 10
max_requests_per_second = 100

[[rpc_endpoints]]
chain = "optimism"
url = "wss://optimism-mainnet.infura.io/ws/v3/YOUR_API_KEY"
weight = 10
max_requests_per_second = 100

[[rpc_endpoints]]
chain = "optimism"
url = "wss://optimism.publicnode.com"
weight = 5
max_requests_per_second = 50

[[rpc_endpoints]]
chain = "optimism"
url = "wss://rpc.ankr.com/optimism_ws/YOUR_API_KEY"
weight = 8
max_requests_per_second = 80

[[rpc_endpoints]]
chain = "optimism"
url = "wss://optimism.getblock.io/YOUR_API_KEY/mainnet/"
weight = 7
max_requests_per_second = 70

# Polygon endpoints
[[rpc_endpoints]]
chain = "polygon"
url = "wss://polygon-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
weight = 10
max_requests_per_second = 100

[[rpc_endpoints]]
chain = "polygon"
url = "wss://polygon-mainnet.infura.io/ws/v3/YOUR_API_KEY"
weight = 10
max_requests_per_second = 100

[[rpc_endpoints]]
chain = "polygon"
url = "wss://polygon-bor.publicnode.com"
weight = 5
max_requests_per_second = 50

[[rpc_endpoints]]
chain = "polygon"
url = "wss://rpc.ankr.com/polygon_ws/YOUR_API_KEY"
weight = 8
max_requests_per_second = 80

[[rpc_endpoints]]
chain = "polygon"
url = "wss://polygon.getblock.io/YOUR_API_KEY/mainnet/"
weight = 7
max_requests_per_second = 70

# Base endpoints
[[rpc_endpoints]]
chain = "base"
url = "wss://base-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
weight = 10
max_requests_per_second = 100

[[rpc_endpoints]]
chain = "base"
url = "wss://base-mainnet.infura.io/ws/v3/YOUR_API_KEY"
weight = 10
max_requests_per_second = 100

[[rpc_endpoints]]
chain = "base"
url = "wss://base.publicnode.com"
weight = 5
max_requests_per_second = 50

[[rpc_endpoints]]
chain = "base"
url = "wss://rpc.ankr.com/base_ws/YOUR_API_KEY"
weight = 8
max_requests_per_second = 80

# BSC endpoints
[[rpc_endpoints]]
chain = "bsc"
url = "wss://bsc.publicnode.com"
weight = 5
max_requests_per_second = 50

[[rpc_endpoints]]
chain = "bsc"
url = "wss://rpc.ankr.com/bsc_ws/YOUR_API_KEY"
weight = 8
max_requests_per_second = 80

[[rpc_endpoints]]
chain = "bsc"
url = "wss://bsc.getblock.io/YOUR_API_KEY/mainnet/"
weight = 7
max_requests_per_second = 70

[[rpc_endpoints]]
chain = "bsc"
url = "wss://bsc-mainnet.nodereal.io/ws/v1/YOUR_API_KEY"
weight = 8
max_requests_per_second = 80

# Chain-specific configurations
[chains]
enabled = ["ethereum", "arbitrum", "optimism", "polygon", "base", "bsc"]

[chains.ethereum]
chain_id = 1
multicall3_address = "0xcA11bde05977b3631167028862bE2a173976CA11"
flashloan_providers = ["aave-v3", "balancer", "uniswap-v3"]
max_gas_price_gwei = 150.0
min_profit_threshold_eth = 0.015
block_time_ms = 12000

[chains.arbitrum]
chain_id = 42161
multicall3_address = "0xcA11bde05977b3631167028862bE2a173976CA11"
flashloan_providers = ["aave-v3", "radiant"]
max_gas_price_gwei = 2.0
min_profit_threshold_eth = 0.01
block_time_ms = 250

[chains.optimism]
chain_id = 10
multicall3_address = "0xcA11bde05977b3631167028862bE2a173976CA11"
flashloan_providers = ["aave-v3"]
max_gas_price_gwei = 2.0
min_profit_threshold_eth = 0.01
block_time_ms = 2000

[chains.polygon]
chain_id = 137
multicall3_address = "0xcA11bde05977b3631167028862bE2a173976CA11"
flashloan_providers = ["aave-v3", "0vix"]
max_gas_price_gwei = 300.0
min_profit_threshold_eth = 0.012
block_time_ms = 2000

[chains.base]
chain_id = 8453
multicall3_address = "0xcA11bde05977b3631167028862bE2a173976CA11"
flashloan_providers = ["aave-v3"]
max_gas_price_gwei = 2.0
min_profit_threshold_eth = 0.01
block_time_ms = 2000

[chains.bsc]
chain_id = 56
multicall3_address = "0xcA11bde05977b3631167028862bE2a173976CA11"
flashloan_providers = ["venus", "radiant"]
max_gas_price_gwei = 10.0
min_profit_threshold_eth = 0.018
block_time_ms = 3000

# MEV Strategies Configuration
[strategies]
enabled = [
    "dex-arb",
    "flash-loan-arb",
    "triangular-arb",
    "cross-chain-arb",
    "liquidation",
    "backrun",
    "jit-liquidity",
    "cex-dex-arb",
    "mev-share",
    "atomic-arb",
    "statistical-arb"
]

[strategies.dex-arb]
enabled = true
dexes = ["uniswap-v2", "uniswap-v3", "sushiswap", "curve", "balancer", "pancakeswap"]
min_roi = 0.015
max_slippage = 0.005

[strategies.flash-loan-arb]
enabled = true
providers = ["aave-v3", "balancer", "uniswap-v3", "radiant", "euler"]
max_leverage_multiplier = 5
min_roi = 0.02

[strategies.triangular-arb]
enabled = true
max_hops = 3
min_roi = 0.018

[strategies.cross-chain-arb]
enabled = true
bridges = ["stargate", "hop", "across", "synapse", "celer"]
min_roi = 0.025
max_bridge_time_seconds = 600

[strategies.liquidation]
enabled = true
protocols = ["aave-v3", "compound-v3", "euler", "radiant", "venus"]
min_health_factor = 1.05
min_roi = 0.03

[strategies.sandwich]
enabled = false  # Disabled for ethical reasons
min_target_size_usd = 50000.0
max_frontrun_gas_gwei = 300.0

[strategies.backrun]
enabled = true
target_types = ["liquidation", "large-swap", "oracle-update"]
min_roi = 0.012

[strategies.jit-liquidity]
enabled = true
protocols = ["uniswap-v3", "pancakeswap-v3"]
min_roi = 0.025

[strategies.cex-dex-arb]
enabled = true
exchanges = ["binance", "coinbase", "okx", "bybit"]
min_roi = 0.02
max_latency_ms = 500

[strategies.nft-arb]
enabled = false
marketplaces = ["opensea", "blur", "x2y2"]
min_roi = 0.05

[strategies.mev-share]
enabled = true
relays = ["flashbots", "bloxroute"]
min_roi = 0.015

[strategies.atomic-arb]
enabled = true
min_roi = 0.012

[strategies.statistical-arb]
enabled = true
confidence_threshold = 0.95
min_roi = 0.02

# Risk Management
[risk]
max_position_size_eth = 100.0
max_daily_loss_eth = 500.0
enable_kill_switch = true
kill_switch_loss_threshold_eth = 1000.0
required_safety_score = 70
blacklisted_tokens = [
    "LUNA",
    "UST",
    "FTT",
    "CELR"
]
whitelisted_tokens = [
    "WETH",
    "USDC",
    "USDT",
    "DAI",
    "WBTC",
    "LINK",
    "UNI",
    "AAVE",
    "CRV",
    "SUSHI",
    "MATIC"
]

# Execution Configuration
[execution]
max_concurrent_trades = 5
default_slippage = 0.005
private_mempool = true
relays = ["flashbots", "bloxroute", "mev-share", "eden", "manifold"]
gas_strategy = "adaptive"  # adaptive, aggressive, conservative
max_priority_fee_gwei = 3.0
target_block_delay = 1

# Monitoring Configuration
[monitoring]
enable_alerts = true
alert_channels = ["telegram", "discord", "email"]
metrics_retention_days = 30
enable_grafana = true
prometheus_endpoint = "http://localhost:9090"