[package]
name = "rust-mev-engine"
version = "3.6.0"
edition = "2021"
authors = ["ArbitrageX Team"]

[dependencies]
# Async runtime
tokio = { version = "1.35", features = ["full"] }
tokio-stream = "0.1"

# Ethereum
ethers = { version = "2.0", features = ["ws", "rustls", "abigen", "ipc"] }
ethers-core = "2.0"
ethers-providers = "2.0"
ethers-signers = "2.0"
ethers-middleware = "2.0"

# HTTP client
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
hyper = { version = "0.14", features = ["full"] }
warp = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# Database
diesel = { version = "2.1", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "2.1"
r2d2 = "0.8"

# Logging and monitoring
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
prometheus = "0.13"
prometheus-hyper = "0.1"

# Utils
anyhow = "1.0"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
async-trait = "0.1"
dashmap = "5.5"
parking_lot = "0.12"

# Cryptography
hex = "0.4"
sha3 = "0.10"

# Rate limiting
governor = "0.6"
nonzero_ext = "0.3"

# Priority queue
priority-queue = "1.3"

# Environment variables
dotenv = "0.15"

[dev-dependencies]
criterion = "0.5"
mockito = "1.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[[bin]]
name = "mev-engine"
path = "src/main.rs"