[package]
name = "mev-engine-minimal"
version = "3.6.0"
edition = "2021"

[features]
# Conjunto mínimo para escaneo y utilidades (no toca tu binario actual)
scanners = ["dep:eyre", "dep:petgraph", "dep:futures-util"]
# EVM (event scanner con ethers). Habilita WebSocket solo cuando lo necesites.
evm = ["scanners", "dep:ethers"]

[dependencies]
# Async runtime - minimal
tokio = { version = "1.35", features = ["rt-multi-thread", "macros", "time"] }

# HTTP client - minimal
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }

# Database - simplified
postgres = { version = "0.19", features = ["with-chrono-0_4", "with-serde_json-1"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utils
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }

# Environment variables
dotenv = "0.15"

# UUID generation
uuid = { version = "1.6", features = ["v4"] }

# Optional dependencies for scanners
eyre = { version = "0.6", optional = true }
petgraph = { version = "0.6", optional = true }
ethers = { version = "2", default-features = false, features = ["ws","rustls"], optional = true }
futures-util = { version = "0.3", optional = true }

[[bin]]
name = "mev-engine-minimal"
path = "src/minimal.rs"

[[bin]]
name = "mev-scanner"
path = "src/bin/mev_scanner.rs"
required-features = ["scanners"]

[profile.dev]
opt-level = 1
debug = false
