name: Build Rust MEV Engine

on:
  workflow_dispatch:
  push:
    paths:
      - 'rust-mev-engine/**'
      - '.github/workflows/build-rust-mev.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust-mev-engine/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build MEV Engine (Minimal)
        run: |
          cd rust-mev-engine
          cargo build --release --bin mev-engine-minimal
          strip target/release/mev-engine-minimal
          mv target/release/mev-engine-minimal target/release/mev-engine
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mev-engine-linux-x64
          path: rust-mev-engine/target/release/mev-engine
          
      - name: Create binaries directory
        run: mkdir -p binaries
      
      - name: Copy binary
        run: |
          cp rust-mev-engine/target/release/mev-engine binaries/
          chmod +x binaries/mev-engine
          ls -lh binaries/
      
      - name: Commit binary
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add binaries/mev-engine
          git diff --quiet && git diff --staged --quiet || git commit -m "Build: Add compiled MEV engine binary [skip ci]"
          git push || true
